// Generated by scripts/build-wp4-launcher.mjs.
namespace TeamForge.Launcher;

internal static class RuntimePins
{
    internal const string ManifestSha256 = "41aec99d8011bd084e95d41957202de83113d7c3d58d272219e4e2bd53a410a2";
    internal const string LoaderSha256 = "5ef4fc80a4e835d1262c1c9aaacd19eb944992dbad4e2f11b1941091d5500fe5";
}
