// Generated by scripts/build-runtime-bundle.mjs.
namespace EunSung.TeamForge
{
    internal static class TeamForgeRuntimeManifest
    {
        internal const string ExpectedSha256 = "24f0aec7aff0c81336d33ac067196c55486b2b2969e74df35737b11e89d99fad";
        internal const string ProductVersion = "0.5.1";
    }
}
